### ISSUE TITLE
You can add a field of iscompleted in Todo

### ISSUE THREAD

**Issue by govardhanshah456** [Kritika30032002/To-Do-List-Application#1]

**Comment by Kritika30032002** [comment]
Do you want to work on this issue? @govardhanshah456

**Comment by govardhanshah456** [comment]
Nope, just suggested some sort of enhancement possible while browsing repos.

**Comment by Kritika30032002** [comment]
okay Thank for your suggestion

**Comment by abhishek-kumar-91** [comment]
I want to work on this issue, Can you assign me?
