### ISSUE TITLE
Fixing the buttons

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Kritika30032002/To-Do-List-Application#106]
When we hover over the buttons, it is disturbing the UI. Please check in the video below.

https://github.com/Kritika30032002/To-Do-List-Application/assets/102857774/ffb8698f-c928-4e89-97eb-a6909e5a7467

Please assign this to me; I will fix it.

**Comment by Niraj-1729** [comment]
I believe that I can make a meaningful contribution by addressing this issue. I have experience in Frontend development and I have worked on various projects. I am eager to work on this specific problem.
Kindly assign this to me !!

THANKS for your consideration.
