### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by sahashorha** [Kritika30032002/To-Do-List-Application#108]
Hello kritika , in your amazing to do list there is no favicon. Favicons help us quickly visually match every browser tab with a certain website. Kritika can u assign me this task

**Comment by Niraj-1729** [comment]
I believe that I can make a meaningful contribution by addressing this issue. I have experience in Frontend development and I have worked on various projects. I am eager to work on this specific problem.
Kindly assign this to me !! 

THANKS for your consideration.

**Comment by divyansh-4** [comment]
Hi @Kritika30032002 , incase this issue isn't closed yet, I'd love to take this up and get it done today

**Comment by Kritika30032002** [comment]
@Niraj-1729  r u working on this?

**Comment by Niraj-1729** [comment]
yes
