### ISSUE TITLE
Responsiveness in mobile and tablet view

### ISSUE THREAD

**Issue by Avinash-31** [Kritika30032002/To-Do-List-Application#110]
Hey can u assign me with this task...I will make the website responsive

![image](https://github.com/Kritika30032002/To-Do-List-Application/assets/98730174/a76ae500-c90e-4b58-ac36-1b77c5b73024)

**Comment by Aniket3063** [comment]
Hello @Kritika30032002, can u assign this issue to me. I can fix the responsiveness asap.
