### ISSUE TITLE
Implement Mobile Responsiveness

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Kritika30032002/To-Do-List-Application#114]
The UI doesn't appear properly on mobile view and needs to be made responsive. Please refer to the screenshot below for clarity.

![Screenshot 2023-10-11 021538](https://github.com/Kritika30032002/To-Do-List-Application/assets/102857774/5c212040-97b8-4e65-8b75-af72133ec3d9)

I will take work on this issue. Kindly assign it to me.

**Comment by Kritika30032002** [comment]
duplicate
