### ISSUE TITLE
Refactor Home Page UI

### ISSUE THREAD

**Issue by dipanshparmar** [Kritika30032002/To-Do-List-Application#115]
I feel like there is still room for improvement in the application UI part. I would love to make it a little better and more accessible.

**Comment by dipanshparmar** [comment]
@Kritika30032002 Can you please assign this to me?

**Comment by dipanshparmar** [comment]
I'm no longer looking forward to work on this. If anyone wants to take this, please go ahead.

**Comment by RonitBaranwal** [comment]
Can I work on this issue?

**Comment by balaraju-nerati** [comment]
Hey @Kritika30032002  as no one is working on this issue, I would like to get assigned for this.

**Comment by balaraju-nerati** [comment]
Thanks @Kritika30032002 I'll soon start work on it
