### ISSUE TITLE
Feature Request: Search Functionality

### ISSUE THREAD

**Issue by yahyaa19** [Kritika30032002/To-Do-List-Application#118]
I would like to request the addition of a "Search" feature in our To-Do List Application. This feature will enhance user experience and make it easier for users to find and sort tasks based on their preferences.

**Search Bar:**
Add a search input field that allows users to search for tasks based on keywords.
Tasks should be filtered as the user types in the search input.

**Benefits:**
This feature will improve task management and organization, especially for users with a large number of tasks.
Users can quickly find specific tasks or focus on tasks that are still pending or completed.

Please consider implementing this feature as it will be a valuable addition to our application. If you have any questions or need further information, please don't hesitate to reach out. Thank you for your attention to this feature request.

**Comment by yahyaa19** [comment]
Hey @Kritika30032002 this is cool repository. I would like to Contribute to it and see it grow.
Allow me to implement this feature by Assigning me this Issue.

**Comment by Kritika30032002** [comment]
great feature.

**Comment by Mayank77maruti** [comment]
Hey @Kritika30032002 , can you please assign this task to me , I am eager to work on this task.
