### ISSUE TITLE
UI changes in 'Input Box' and fixing 'Add Task' button background underflow. 

### ISSUE THREAD

**Issue by avg77** [Kritika30032002/To-Do-List-Application#129]
Hey there, @Kritika30032002! 
I'd like to make some changes in the CSS style sheet to improve the UI of the 'Input Box'. This will make it more consistent with the background of the website. 
Secondly, i propose to fix the background underflow in the 'Add Task' button.

I have attached the necessary screenshots to give you an idea on improvements and fixes. 

1) Before:-
![bef1](https://github.com/Kritika30032002/To-Do-List-Application/assets/91598955/480fbbe2-4580-446c-ad6d-e7df3f1613e8)

2) After:-
![aft1](https://github.com/Kritika30032002/To-Do-List-Application/assets/91598955/d1c0ac77-ebb3-41cc-9c4d-654a3c0d06de)

I'm ready to discuss and accommodate changes as per your requirements.
Kindly assign me this issue under appropriate tags.

**Comment by Kritika30032002** [comment]
Cannot identify change.
brief it

**Comment by avg77** [comment]
1) Changed the background color of the add task box from transparent black to transparent blue
2) The 'ADD TASK' button's blue background doesn't fit perfectly with the button size from corners. So fixed that

**Comment by Kritika30032002** [comment]
okay
