### ISSUE TITLE
Feature Request: Sorting functionality

### ISSUE THREAD

**Issue by Shahidkhatrii** [Kritika30032002/To-Do-List-Application#135]
I would like to introduce Sort feature that will sort the task list according to due date.

**Comment by asheshmandal2003** [comment]
Sorry, I did not noticed that this issue already have an assignee.

**Comment by Shahidkhatrii** [comment]
I have made changes as per new UI of application 
![Screenshot_20231020_031554](https://github.com/Kritika30032002/To-Do-List-Application/assets/104732343/c594c9f9-645e-4ba9-88d5-590409cba68d)
![Screenshot_20231020_031632](https://github.com/Kritika30032002/To-Do-List-Application/assets/104732343/04be6eb1-6484-4dbd-b3b0-88fd63cbb4f0)
@Kritika30032002

**Comment by Kritika30032002** [comment]
merged
