### ISSUE TITLE
Better Dark theme

### ISSUE THREAD

**Issue by harshu0001** [Kritika30032002/To-Do-List-Application#142]
I guess the page requires a better dark theme, as it will look more beautiful.
Please assign this issue to me.
Thanks
!

**Comment by DanielZhang111** [comment]
Is this still up for grabs:?

**Comment by Kritika30032002** [comment]
@harshu0001  r u working on this?

**Comment by harshu0001** [comment]
YES!

I'm.. just need one more day... will get it done by tomorrow night.

**Comment by saurabhgdeshmukh** [comment]
Please assign this task to me.

**Comment by devesh-dkp** [comment]
Can you assign this task to me? I want to work on this.

**Comment by Mayank77maruti** [comment]
Hi @Kritika30032002 , Can You Please Assign This Issue to Me Since I have already worked On a similar Issue Earlier , i believe , I will be able to tackle this issue Nicely.

**Comment by Surajit0573** [comment]
I can do this, please assign me !!

**Comment by Kritika30032002** [comment]
program name?

**Comment by Kritika30032002** [comment]
@devesh-dkp Are You working on this?

**Comment by devesh-dkp** [comment]
Yes, But I am not able to come up with any significant change.

**Comment by Kritika30032002** [comment]
Do you want to continue with this or I can assign this to someone else?

**Comment by Mayank77maruti** [comment]
Hey @Kritika30032002 , I want to do this task, please do assign it to me.

**Comment by Mayank77maruti** [comment]
![darkmode](https://github.com/Kritika30032002/To-Do-List-Application/assets/125661248/68b687ae-cbcc-4667-a465-1a4ebeba6d9c)
Mam does this look good or do i need to change the colors , please do let me know.

**Comment by Kritika30032002** [comment]
Keep in mind, you are making to do list 
so please change color theme accordingly
