### ISSUE TITLE
Due Date & Submit button overflows the form

### ISSUE THREAD

**Issue by anupjeejo** [Kritika30032002/To-Do-List-Application#155]
->On smaller screens the Due date and Submit button overflows out of the form.

SCREEN-SHOTS For reference

#Screent-Shot-1
![Screenshot (48)](https://github.com/Kritika30032002/To-Do-List-Application/assets/58913401/1026a012-f3d6-4246-a689-879749dc928c)
 
#Screent-Shot-1
![Screenshot (49)](https://github.com/Kritika30032002/To-Do-List-Application/assets/58913401/434ea1b3-faae-4f5d-8231-7f2580b3fecf)

**Comment by anupjeejo** [comment]
@Kritika30032002, Kindly assign me this issue, I will solve it as soon as possible.

**Comment by hamzailyas237** [comment]
I want to work on this. Assign it to me
