### ISSUE TITLE
Background issue image

### ISSUE THREAD

**Issue by divyansh14kr** [Kritika30032002/To-Do-List-Application#162]
Upon adding new tasks the background image seems to keep getting bigger and upon deletion of those tasks the image gets shrunk by the same size
Please assign me this issue, I would like to work on it

<img width="1440" alt="Screenshot 2023-10-16 at 2 17 36 PM" src="https://github.com/Kritika30032002/To-Do-List-Application/assets/118956824/39574f77-304b-4135-8289-a8491a5ec63b">
<img width="1440" alt="Screenshot 2023-10-16 at 2 17 53 PM" src="https://github.com/Kritika30032002/To-Do-List-Application/assets/118956824/71bb54f8-a654-4a70-a3af-0de199c067f9">
<img width="1440" alt="Screenshot 2023-10-16 at 2 18 03 PM" src="https://github.com/Kritika30032002/To-Do-List-Application/assets/118956824/0a3dd5dd-cd67-4162-84c4-eb6279e739b2">
<img width="1440" alt="Screenshot 2023-10-16 at 2 18 11 PM" src="https://github.com/Kritika30032002/To-Do-List-Application/assets/118956824/29193f53-449b-4703-9cda-766ce94ca2a4">

**Comment by Kritika30032002** [comment]
great observation
