### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Manideep711** [Kritika30032002/To-Do-List-Application#18]
I want to add a toggler which toggles between dark and light mode

**Comment by Kritika30032002** [comment]
and rest changes of dark mode?

**Comment by Manideep711** [comment]
background to black and text to white

**Comment by Kritika30032002** [comment]
okay

**Comment by mohitsaini07** [comment]
Hi Kritika, I would like to work on this issue if available.

**Comment by Mayank-Creater** [comment]
Please assign this issue to me

**Comment by Kritika30032002** [comment]
@Manideep711  Are you working on this?

**Comment by Dhandeep10** [comment]
Can you please assign me this issue

**Comment by Manideep711** [comment]
yes iam working on it

**Comment by Kritika30032002** [comment]
> yes iam working on it

okay
