### ISSUE TITLE
I want to improve UI of this app

### ISSUE THREAD

**Issue by taqui-786** [Kritika30032002/To-Do-List-Application#2]
@Kritika30032002  want to improve the UI of this todo App .. 
Please assign me .

**Comment by krishprav** [comment]
Please assign me .

**Comment by priyamaggarwal18** [comment]
Hello @taqui-786 . Can you please assign this issue to me.
I'll improve UI and make it best.

**Comment by Kritika30032002** [comment]
This is already assigned to someone.

You can Get assigned another issue or create the one for yourself.

**Comment by priyamaggarwal18** [comment]
oh that great. Thanks for helping @Kritika30032002 .

**Comment by prafull904434** [comment]
mam,
may i work with this issue,
can you assign to me

**Comment by Kritika30032002** [comment]
@prafull904434  This is already assigned to someone.

You can Get assigned another issue or create the one for yourself.
