### ISSUE TITLE
feat: Add a preloader to the website.

### ISSUE THREAD

**Issue by purnasth** [Kritika30032002/To-Do-List-Application#209]
# Issue Title: Add Preloader

## Issue Description
I propose adding a preloader to improve the user experience while the website is loading. A preloader provides visual feedback to users that the page is loading, enhancing the overall aesthetics of the website.

## Additional Information (if available)
If there are specific design preferences for the preloader or any guidelines for contributing to the repository, please provide them to ensure it aligns with the project's goals.

I am eager to contribute this enhancement to the project and look forward to your guidance and feedback.

**Comment by Kritika30032002** [comment]
make it something related to to do list

like while loading it is showing that writing todo on paper (not content its effect)

**Comment by purnasth** [comment]
Sure.. I'll try to work on what you suggest.

**Comment by Kritika30032002** [comment]
if you have any doubt or want any confirmation, you can contact me on discord or linkedin
