### ISSUE TITLE
Todo Delete button not working

### ISSUE THREAD

**Issue by love-sonkar** [Kritika30032002/To-Do-List-Application#219]
when you click to Delete button the to do is not deleting

# video 

https://github.com/Kritika30032002/To-Do-List-Application/assets/82786865/42dce076-5394-4f95-9088-61f2916366a2

**Comment by VadimDez** [comment]
@love-sonkar @Kritika30032002  Can I take a look at this one?

**Comment by VadimDez** [comment]
@Kritika30032002 please review my pull request
