### ISSUE TITLE
Minor fix: If no task is added to our list we shouldn't display the Tasks heading

### ISSUE THREAD

**Issue by hustlerZzZ** [Kritika30032002/To-Do-List-Application#23]
Before
![image](https://github.com/Kritika30032002/To-Do-List-Application/assets/102817420/216457a3-444f-43f1-86bf-6db1cff77125)

After 
![image](https://github.com/Kritika30032002/To-Do-List-Application/assets/102817420/f7e59cd2-0120-4c0a-b865-61348567599f)

I think we should implement this feature in our project.

**Comment by SiddharthaKR** [comment]
Hi there, I'd be happy to look into the mentioned bug. Please assign this to me

**Comment by Kritika30032002** [comment]
It is already assigned.
 You can work on another issue.
