### ISSUE TITLE
Redesigned the Add Voice Command button 

### ISSUE THREAD

**Issue by sanskarOH** [Kritika30032002/To-Do-List-Application#231]
Please assign this issue to me.

**Comment by sanskarOH** [comment]
@Kritika30032002  please assign this issue to me

**Comment by K-Saniya** [comment]
@Kritika30032002 I am interested in contributing . Please assign it to me!!

**Comment by sanskarOH** [comment]
> @Kritika30032002 I am interested in contributing . Please assign it to me!!

I already made a pr immediately after opening the issue
