### ISSUE TITLE
issue when handling due date. .If a date is not selected or is invalid, an error message prompts the user to select a valid due date.

### ISSUE THREAD

**Issue by NandishM0618** [Kritika30032002/To-Do-List-Application#238]
![issue2](https://github.com/Kritika30032002/To-Do-List-Application/assets/100901899/d3d6cbe6-ba69-472f-b08c-46bc67e72667)

**Comment by NandishM0618** [comment]
like if we did'nt specify any due date why should it show due date has already passed. it should alert that please specify a date or other specific messages right?  correct me..

**Comment by rakesh-vajrapu** [comment]
Please assign this issue to me. I'll work on it!

**Comment by rakesh-vajrapu** [comment]
Please assign this issue to me, I'll work on it!

**Comment by nepalivai** [comment]
I tried to solve this as an issue for hours but seems like it takes today's date by default. So, that's fine but it should at least show the **date in the date picker.**

**Comment by NandishM0618** [comment]
@Kritika30032002  I have created a pull request about the issue please review it #242 and any if changes required please update me.
