### ISSUE TITLE
[Bug]: Task label not checked after edit 

### ISSUE THREAD

**Issue by nepalivai** [Kritika30032002/To-Do-List-Application#241]
There is a bug in when you edit the given task.

---To copy issue {steps}:-
1. create a task.
2. click on the green edit box.
3. Rename the label to empty.
4. see the issue

Expected:-
notification telling to enter a label name.

<img width="528" alt="image" src="https://github.com/Kritika30032002/To-Do-List-Application/assets/108126089/1184c003-fabb-44cb-bd28-9e553f5e3cb7">

**Comment by nepalivai** [comment]
Hey @Kritika30032002, Thanks for assigning the job to me but I am not that good at JavaScript work. I work as a UI/UX designer. So I am here to only in-hance my CSS skills for now. currently i am working in [https://github.com/Kritika30032002/To-Do-List-Application/issues/142] This issue. so you can assign that to me.

**Comment by Kritika30032002** [comment]
Okay .

**Comment by Kritika30032002** [comment]
As a participant of which program?

**Comment by Saibhuvan435** [comment]
Hey @Kritika30032002, can you assign this issue to me!
