### ISSUE TITLE
[BUG]  Task bar update while editing a task.

### ISSUE THREAD

**Issue by nepalivai** [Kritika30032002/To-Do-List-Application#244]
The taskbar does not update when I select the edit option.
 
---To copy issue {steps}:-
1. create a new task.
2. click on edit button.
3. see issue. 
(if you're unclear about the issue _priority and date_ did not change.

Expected:-
Them changing.

<img width="548" alt="image" src="https://github.com/Kritika30032002/To-Do-List-Application/assets/108126089/01e0c540-58a8-4b64-ad55-62bbb1550651">

**Comment by nepalivai** [comment]
It would be nice if some suggest the best UI design for the new button.

**Comment by Kritika30032002** [comment]
UI depends on creative mind of UI/UX. Nothing specific but it should look good

**Comment by Kritika30032002** [comment]
Participant of which program?
