### ISSUE TITLE
Style the footer

### ISSUE THREAD

**Issue by Swap-nil-2003** [Kritika30032002/To-Do-List-Application#246]
The footer needs to stand out from the rest of the page. So, would be nice if that can be fixed!

**Comment by Mayank77maruti** [comment]
Hi @Kritika30032002 , Can You Please Assign This Task To Me Under Code Peak'23.

**Comment by Kritika30032002** [comment]
Mention the program of your participation.

**Comment by Swap-nil-2003** [comment]
I would like to make this contribution under Codepeak 2023 @Kritika30032002

**Comment by Swap-nil-2003** [comment]
@Kritika30032002 opened a PR in #258

**Comment by Albert-2** [comment]
hey @Kritika30032002  i would like to work on this issue please assign me it under codepeak'23 if no one is still working on it......
Thank you.... :)
