### ISSUE TITLE
Fix Button Margin

### ISSUE THREAD

**Issue by smty2018** [Kritika30032002/To-Do-List-Application#248]
Currently , there is not spacing between select priority and date. Want to add proper margin so it looks good.
![image](https://github.com/Kritika30032002/To-Do-List-Application/assets/74114936/6ab65a74-8711-4e1a-b663-bac08151f059)
 @Kritika30032002 Can you please assign this to me under codepeak

**Comment by Kritika30032002** [comment]
not required
