### ISSUE TITLE
Webstite is not well Responsive 

### ISSUE THREAD

**Issue by Devesh-Daku** [Kritika30032002/To-Do-List-Application#249]
When you opne the website in mobile phone the top text animation makes it annoying  to click on text 
even the input also get very small 
is suggest adding a media query properly defined for mobile devices 
![todoproject](https://github.com/Kritika30032002/To-Do-List-Application/assets/121988601/50019f5d-ebfa-4f8a-aed4-4a7bf1395b9e)

**Comment by Devesh-Daku** [comment]
i'd like to solve the issue

**Comment by ayann07** [comment]
As a KWOC Contributor, I would like to work on this issue.

**Comment by Kritika30032002** [comment]
@Devesh-Daku  Program name?

**Comment by Devesh-Daku** [comment]
Please assign a codepeak label

**Comment by Albert-2** [comment]
hey @Kritika30032002
I would like to contribute to this issue
Will you please assign me this issue if no one is still working on it
THANK YOU.....!!
