### ISSUE TITLE
Duplicate Tasks Allowed

### ISSUE THREAD

**Issue by Arpit01Goel** [Kritika30032002/To-Do-List-Application#253]
While making tasks , even if you choose two tasks with same name,priority and data ; it will just add the task without raising any query. This should be solved to make no two tasks on same day have same name.

**Comment by Arpit01Goel** [comment]
KWoC

**Comment by Arpit01Goel** [comment]
> program name?

KWoC

**Comment by Kushalgt** [comment]
I want to work on this

**Comment by Yash-Ainapure** [comment]
Heyy @Kritika30032002  , If @Kushalgt  isn't working, can you assign it to me?

**Comment by Kritika30032002** [comment]
@Kushalgt  Do you want to work on this?

**Comment by Yash-Ainapure** [comment]
@Kritika30032002 , As @Kushalgt  hasn't replied in 3 days I I will complete this task.
