### ISSUE TITLE
Sort By date Not working

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/To-Do-List-Application#254]

**Comment by coldrohak** [comment]
@Kritika30032002 i can work on this

**Comment by Kritika30032002** [comment]
under program name?

**Comment by Yash-Ainapure** [comment]
Heyy @Kritika30032002 , I would like to take this issue up.

**Comment by Yash-Ainapure** [comment]
Heyy @Kritika30032002 , the sort by date is working fine.
there is no issue with it.
