### ISSUE TITLE
Add new functionality as 'Description'

### ISSUE THREAD

**Issue by Sami3160** [Kritika30032002/To-Do-List-Application#255]
I would like to add new functionality as Description. It will act as an optional description for the task where we can record tasks with more details.
![Screenshot (72)](https://github.com/Kritika30032002/To-Do-List-Application/assets/110652247/76d7270e-046e-40c4-b15b-6ee8ccdd39a1)

By add button the added data will be displayed in below list and data does get added in local storage,
![Screenshot (73)](https://github.com/Kritika30032002/To-Do-List-Application/assets/110652247/08f0bd16-5dfd-4a41-9ef4-59a1b9a0f88a)

Well, by edit button we can also change the description and it also saves in local storage.
![Screenshot (74)](https://github.com/Kritika30032002/To-Do-List-Application/assets/110652247/9a6482f0-722f-4654-85e0-cf2ea36198bc)

please do acknowledge my new feature that ill be implementing...😊✌and assign me for this task please

**Comment by Kritika30032002** [comment]
UI Need to be improved

**Comment by Kritika30032002** [comment]
program name?

**Comment by Kritika30032002** [comment]
adjustment of Description into the website has to be done properly.

**Comment by Kritika30032002** [comment]
take sync with current website before adding this as new feature is added

**Comment by Sami3160** [comment]
> take sync with current website before adding this as new feature is added

well the changes were made long time ago and i sent pr also, now im trying to sync a fork with an upstream repository, and it says to discard the 2 major commits i have done and their are so many branch conflict while syncing. Their are are so many changes that will be removed. Please check my pull request also, during pull requests i encountered no branch conflicts. Please tell me what to do

**Comment by Kritika30032002** [comment]
firstly you shouldn't work on that long time ago
secondly i cannot accept pr with conflicts as it will destroy the whole website functioning 
What u can do is you can sync your repo with my updated one and add the required changes codelines and check its functioning

**Comment by Kritika30032002** [comment]
create a new pr after that
