### ISSUE TITLE
Adding a new mic icon in voice command

### ISSUE THREAD

**Issue by Souvik34** [Kritika30032002/To-Do-List-Application#262]
Usually the text start voice command won't seem cool. Instead I can use these logo to make it more concise and clear and clean.
<img width="865" alt="Screenshot 2023-12-09 185927" src="https://github.com/Kritika30032002/To-Do-List-Application/assets/98397984/ed784421-2697-4b50-bf7c-babed53f5b40">

Here I can integrate this type of logo
<img width="838" alt="Screenshot 2023-12-09 185907" src="https://github.com/Kritika30032002/To-Do-List-Application/assets/98397984/e6c521ff-bf15-4a0b-be18-17a56fce2ef2">

**Comment by Kritika30032002** [comment]
program name?

**Comment by Kritika30032002** [comment]
#257 includes this issue
