### ISSUE TITLE
adding selection button

### ISSUE THREAD

**Issue by SoumodeepDas** [Kritika30032002/To-Do-List-Application#27]

**Comment by SoumodeepDas** [comment]
i want to add one more button showing all the list,the lists which are done,the list which are completed.It would make it look better and will be beneficial for the user if large list is there

**Comment by Kritika30032002** [comment]
explain this

**Comment by SoumodeepDas** [comment]
![Screenshot 2023-10-02 113803](https://github.com/Kritika30032002/To-Do-List-Application/assets/111363923/54a0bd88-95e0-4665-be24-ab411abc9679)

**Comment by SoumodeepDas** [comment]
i am talking about this.....

**Comment by Kritika30032002** [comment]
okay
