### ISSUE TITLE
mail/notification for reminder

### ISSUE THREAD

**Issue by Tanmay0215** [Kritika30032002/To-Do-List-Application#273]
we can add a feature to mail the user or notify on the brower to complete the task before some fixed time the task is supposed to end

**Comment by Kritika30032002** [comment]
great  
get it approved before adding what you will do in this

**Comment by YashSachan2** [comment]
@Kritika30032002 Can I work on this issue under Codepeak?

**Comment by Kritika30032002** [comment]
@Tanmay0215 Are you working on this?

**Comment by Tanmay0215** [comment]
no @YashSachan2 can continue 
i don't have the required knowledge for this

**Comment by Yash-Ainapure** [comment]
@Kritika30032002  , I would like to take this issue.

**Comment by YashSachan2** [comment]
@Kritika30032002 Please assign me this issue as @Tanmay0215 has replied

**Comment by YashSachan2** [comment]
> no @YashSachan2 can continue i don't have the required knowledge for this

Okk bro

**Comment by YashSachan2** [comment]
@Kritika30032002 I have made a pr for this issue .Please look into it and assign me the points.
