### ISSUE TITLE
Improving UI add your task card

### ISSUE THREAD

**Issue by HarshitSharma4** [Kritika30032002/To-Do-List-Application#277]
The current UI for the "Add your task card" feature needs improvement as all components appear very close to each other, making the interface less user-friendly and not interactive.
 
![Screenshot from 2023-12-10 17-57-32](https://github.com/Kritika30032002/To-Do-List-Application/assets/106171546/6f49e558-763e-4b46-9728-0f9d8ed6254a)

**Comment by Kritika30032002** [comment]
which components?

program name?

**Comment by HarshitSharma4** [comment]
component "add your task below and tasks"
program name "codepeak"

**Comment by Kritika30032002** [comment]
it has been changing with ongoing issue, working on this
