### ISSUE TITLE
Sorting  of task is not displaying to page

### ISSUE THREAD

**Issue by HarshitSharma4** [Kritika30032002/To-Do-List-Application#278]
The current implementation of task sorting is not displaying correctly on the page, causing users to experience issues with organizing and managing their tasks effectively.
[Screencast from 2023-12-10 18-13-25.webm](https://github.com/Kritika30032002/To-Do-List-Application/assets/106171546/e7731864-d62d-4550-b32d-c6efc7973840)

**Comment by Kritika30032002** [comment]
can be considered under #277
