### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [Kritika30032002/To-Do-List-Application#28]
I want to add User Authentication ,
User has to Sign In ,Sign up and then he can add his tasks so that , 
every user has their own tasks and they can able to see , update, delete , create etc

Please assign this to me , I am very much interested to contribute in hacktoberfest_23 : )

**Comment by Kritika30032002** [comment]
@Bharath-KumarReddy Are you working on this?

**Comment by Kritika30032002** [comment]
Okay you can take your time

**Comment by Bharath-KumarReddy** [comment]
Here you go I had resolved this issue and 
And changed the project to MERN_STACK with all working functionalities .

I had made a PR #73 , merge it _hacktoberfest_23 : )

**Comment by Bharath-KumarReddy** [comment]
Once check this I had made a PR on the demo branch : )

**Comment by Kritika30032002** [comment]
done
