### ISSUE TITLE
Date reset Issue

### ISSUE THREAD

**Issue by VinayKhedkar** [Kritika30032002/To-Do-List-Application#280]
Once a task is created, the date option doesn't show the current date again but it should reset itself whenever a task is created or edited.

[To-Do List - Google Chrome 2023-12-10 22-50-15 - Trim - Trim.zip](https://github.com/Kritika30032002/To-Do-List-Application/files/13628662/To-Do.List.-.Google.Chrome.2023-12-10.22-50-15.-.Trim.-.Trim.zip)

**Comment by Kritika30032002** [comment]
unable to understand you point
