### ISSUE TITLE
Dark mode issue

### ISSUE THREAD

**Issue by VinayKhedkar** [Kritika30032002/To-Do-List-Application#281]
If the page is set in dark mode and if we refresh the page, it goes into light mode and doesn't continue to be in dark mode.

**Comment by Kritika30032002** [comment]
program name?

**Comment by YashSachan2** [comment]
@Kritika30032002 I wish to contribute to this issue.Please assign it to me under codepeak-23

**Comment by YashSachan2** [comment]
@Kritika30032002 I have made a pr resolving this issue .Please look into it and assign me the points. #291
