### ISSUE TITLE
Improve Responsiveness of page for smaller devices

### ISSUE THREAD

**Issue by anand-harsh** [Kritika30032002/To-Do-List-Application#284]
**Description**: Task form is not responsive for smaller devices

**Screenshot:**

![image](https://github.com/Kritika30032002/To-Do-List-Application/assets/94885893/6f4f41ae-829f-4d4c-8820-d1f3b4a3dc3a)

**Comment by Kritika30032002** [comment]
direct pr is not acceptable
also this is in progress
