### ISSUE TITLE
Text-font and font-style of Website

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Kritika30032002/To-Do-List-Application#298]
Enhance text font for different parts of the website like,
- Header
- Input box
- Buttons
- Tasks added
- With coloring effects and enhanced styling and lightning

**Comment by Avdhesh-Varshney** [comment]
@Kritika30032002 please assign this task to me to work on it under CodePeak'23.

**Comment by jatking03** [comment]
google fonts would be suitable could this issue be re-assigned to me under KWOC'23
