### ISSUE TITLE
[BUG] It is not allowed to create a task having deadline of the same day

### ISSUE THREAD

**Issue by AdityaRaj212** [Kritika30032002/To-Do-List-Application#307]
This to-do list doesn't allow a user to add a task with a deadline on the same day. But it should accept a task that the user wants to complete on the same day.
![Screenshot from 2023-12-21 19-00-50](https://github.com/Kritika30032002/To-Do-List-Application/assets/127577061/afef6631-3caa-445a-b20d-ffa4c8cc518a)

**Comment by AdityaRaj212** [comment]
@Kritika30032002 please assign this task to me under KWOC'23

**Comment by Kritika30032002** [comment]
yes

**Comment by AdityaRaj212** [comment]
Hey @Kritika30032002 You closed this thread, so does that mean that it wasn't a bug and no changes need to be made to rectify this bug, or was it done by mistake?

**Comment by Kritika30032002** [comment]
not bug

**Comment by AdityaRaj212** [comment]
Ok. Thank you for the response.
