### ISSUE TITLE
Animating Logo & Text 

### ISSUE THREAD

**Issue by Dimple-Choudhary** [Kritika30032002/To-Do-List-Application#32]
Can I add a typing effect to the "To-do  List "text and when the text is completed the logo will appear? 

It will improve UX.

will please assign me this issue under hacktoberfest'23?

**Comment by Dimple-Choudhary** [comment]
hey @Kritika30032002  now as  the website is updata, so it will be good if  only text is animated, what do you think?

**Comment by Kritika30032002** [comment]
Yes

**Comment by Kritika30032002** [comment]
if its there then create separate issue for this with screenshot
