### ISSUE TITLE
Footer isn't responsive ! Also the microphone logo isn't properly visible.

### ISSUE THREAD

**Issue by MADHURYAHAIT** [Kritika30032002/To-Do-List-Application#327]
<img width="1680" alt="Screenshot 2024-01-09 at 12 57 16 AM" src="https://github.com/Kritika30032002/To-Do-List-Application/assets/101663118/2dfa71e8-4cfe-4b2c-ae3c-1049742c3212">

Please assign me this ! I can fix it till tomorrow. @Kritika30032002

**Comment by Kritika30032002** [comment]
are you working on it?
