### ISSUE TITLE
Bug: Sort Feature is clearing all the tasks

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/To-Do-List-Application#336]
Got some bug in its working, code is there.

**Comment by atbalaji** [comment]
I would like to work on this issue @Kritika30032002  under IWOC 2.0

**Comment by atbalaji** [comment]
I have created a PR @Kritika30032002 . The fixes also fixed search and sort functionality. I handled the refresh causing tasks to disappear behaviour too by calling init() and removing the duplicate. Is that ok?
