### ISSUE TITLE
Bug: Search button is not working

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/To-Do-List-Application#338]
Code logic is there but there is some bug in its working

**Comment by Bayyana-kiran** [comment]
Can u assign me I will try to do ?

**Comment by Bhupendra3444** [comment]
hey @Kritika30032002  Please assign me this task under iwoc. I want to work on it.

**Comment by NoIdea2001** [comment]
I think the search feature is working perfectly 
can you please share any ss or video for the issue

**Comment by Bayyana-kiran** [comment]
yeah actually it is working another guy has sorted it...

**Comment by Kritika30032002** [comment]
Yes it is done
