### ISSUE TITLE
Implement Task Persistence with Local Storage

### ISSUE THREAD

**Issue by Tholkappiar** [Kritika30032002/To-Do-List-Application#339]
### Issue Title:
Implement Task Persistence with Local Storage

### Description:
Currently, when users add tasks to the todo list on the website, the tasks disappear upon refreshing the page. I propose implementing local storage to store and persist tasks across page reloads, providing a seamless user experience.

### Problem:
After adding tasks, they are not retained upon refreshing the page, resulting in a loss of user-entered data.

### Proposed Solution:
Implement local storage functionality to store and retrieve tasks. This will ensure that tasks remain persistent even after users reload the page.

### Implementation Plan:
1. Identify the relevant sections of the code where tasks are handled.
2. Modify the JavaScript code to interact with local storage for task persistence.
3. Test thoroughly to ensure tasks are retained across page reloads.

**Comment by Kritika30032002** [comment]
its already done

**Comment by Tholkappiar** [comment]
I checked that , there is local storage but it's not working properly, kindly check and assign this issue to me ! The added values are not persisting across refresh , waiting for your valuable response, thankyou for your time and consideration.

**Comment by Kritika30032002** [comment]
check it now(again)

**Comment by Tholkappiar** [comment]
Yeah , now its working good . Thank you !
