### ISSUE TITLE
Adding Recurring tasks functionality 

### ISSUE THREAD

**Issue by Anuragpal010104** [Kritika30032002/To-Do-List-Application#34]
I would like to express my interest in contributing to the project by proposing the addition of recurring task functionality. If possible, could you please consider assigning this issue to me as part of the Hacktoberfest 2023? Thank you for your consideration :)

**Comment by Kritika30032002** [comment]
brief it

**Comment by Anuragpal010104** [comment]
> brief it

There are some task which people have to do daily. So I want to add that like any task is to be done from this date to this date

**Comment by Anuragpal010104** [comment]
Added the due date option
