### ISSUE TITLE
Dark mode theme state is not preserved after reloading 

### ISSUE THREAD

**Issue by Ayush-2301** [Kritika30032002/To-Do-List-Application#341]
After reloading the dark mode theme resets and bugs the theme button

**Comment by Ayush-2301** [comment]
@Kritika30032002 please assign this issue to me under iwoc

**Comment by Kritika30032002** [comment]
i think code is there 
you have to only remove the bug

**Comment by Bhupendra3444** [comment]
hey @Kritika30032002  Please assign me this task under iwoc. I want to work on it.

**Comment by Kritika30032002** [comment]
@Ayush-2301  Are u working on this?
