### ISSUE TITLE
Two-Column Layout for ToDo App

### ISSUE THREAD

**Issue by Tholkappiar** [Kritika30032002/To-Do-List-Application#343]
### More Effective User Experience.

The current vertical layout of the tasks in the to-do app can be enhanced by introducing a two-column layout. This change aims to provide a more visually appealing and user-friendly experience, with the task addition on the left side and task display on the right side.

## Changes Made
- **Two-Column Layout:**
  - Left Column: Task Input
  - Right Column: Task Display

## Design Idea
![Screenshot from 2024-01-14 12-15-22](https://github.com/Kritika30032002/To-Do-List-Application/assets/114584730/2c8a8081-7b48-46fb-b013-1162c301efbc)

**Comment by Tholkappiar** [comment]
Yes working this feat , will update today ! :+1:

**Comment by SoumyadevSaha** [comment]
Hi @Kritika30032002 would like to work on this issue, if it gets stale, or any further improvements required.
