### ISSUE TITLE
[BUG]: Edit Feature Not Dsiplayed Properly

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Kritika30032002/To-Do-List-Application#345]
**Description-**
When the user clicks on the Edit button of the task, it seems that nothing happens after clicking it, and it might seem to the user that the button is not working appropriately. So it need to be fixed when the user clicks on the Edit button it should take the user to the edit bar of the form.

**Video-**

https://github.com/Kritika30032002/To-Do-List-Application/assets/140608790/79b19f0d-e02e-45a1-9261-111a7f465716

**Comment by JiyaGupta-cs** [comment]
@Kritika30032002 Please assign me this issue under IWOC and please also add the labels of "easy" / "medium" / "hard" along with "iwoc2024"

**Comment by geek-nikhil** [comment]
@Kritika30032002 please assign me this i have solved the issue


Uploading 20240119015917.mp4…

**Comment by geek-nikhil** [comment]
@Kritika30032002 please assign me this i have solved the issue


https://github.com/Kritika30032002/To-Do-List-Application/assets/126591020/2fa8b7fc-25cc-494d-bb5b-dc15215493b9

**Comment by Kritika30032002** [comment]
@JiyaGupta-cs are u working on this?

**Comment by geek-nikhil** [comment]
@Kritika30032002 please merge the pr if it is ok.
