### ISSUE TITLE
Sort by priority not wokring

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/To-Do-List-Application#353]
Also make the setting the priority as mandatory

**Comment by Jenis07** [comment]
can you assign me this issue under IWOC?

**Comment by Jenis07** [comment]
![image](https://github.com/Kritika30032002/To-Do-List-Application/assets/100338684/7985c877-31c0-412c-9d34-d7bb1a1b5631)
is this good?

**Comment by Kritika30032002** [comment]
create pr then only i will be able to check or post the video

**Comment by Jenis07** [comment]
Uploading To-Do List and 6 more pages - Profile 1 - Microsoft​ Edge 2024-02-04 21-33-38.mp4…
i have attach the video with this comment

**Comment by Jenis07** [comment]
Uploading To-Do List and 6 more pages - Profile 1 - Microsoft​ Edge 2024-02-04 21-33-38.mp4…

**Comment by Kritika30032002** [comment]
Sort by priority working?

**Comment by Jenis07** [comment]
Yes ma'am

**Comment by Kritika30032002** [comment]
show video
