### ISSUE TITLE
Adding Type in task

### ISSUE THREAD

**Issue by Anuragpal010104** [Kritika30032002/To-Do-List-Application#51]
I have a suggestion in which I can add type of work by using a simple dropdown. I have attached a SS for that. Kindly look into it and if everything is fine assign this issue to me under hacktoberfest 2023.
Ignore the styling for reference only :)
![SS_todo_type](https://github.com/Kritika30032002/To-Do-List-Application/assets/120403013/0f05ebb7-64cc-49b2-b284-6a729117dda3)

**Comment by Kritika30032002** [comment]
this can be added as a filter
