### ISSUE TITLE
Css Improvement and adding eye catching svgs

### ISSUE THREAD

**Issue by priyamaggarwal18** [Kritika30032002/To-Do-List-Application#6]
Hi @Kritika30032002  . Can you please assign this issue to me .
I will improve its CSS and add some eye catching svg.

**Comment by Kritika30032002** [comment]
@priyamaggarwal18 Are you working on this?

**Comment by Tulsi5990** [comment]
Hi @Kritika30032002 can u please assign me this work?

**Comment by sayumimuthu** [comment]
Hi @Kritika30032002 will you be able to assign me this issue?

**Comment by Niraj-1729** [comment]
I believe that I can make a meaningful contribution by addressing this issue. I have experience in Frontend development and I have worked on various projects. I am eager to work on this specific problem.
Kindly assign this to me !!

THANKS for your consideration.
