### ISSUE TITLE
Add default due date of {today} on which task is created

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/To-Do-List-Application#64]

**Comment by Virtual4087** [comment]
Can you assign this to me?

**Comment by Virtual4087** [comment]
Can you clarify this a little?

**Comment by Virtual4087** [comment]
nvm got it

**Comment by Kritika30032002** [comment]
![image](https://github.com/Kritika30032002/To-Do-List-Application/assets/83400697/93d1e2e9-311f-4b6c-be46-6921067aa5e3)


Here when due date is not provided then it showing blank

It should take default of when task is added
