### ISSUE TITLE
unresponsive website

### ISSUE THREAD

**Issue by ashfaque-mustaque** [Kritika30032002/To-Do-List-Application#67]
Hello @Kritika30032002, the website is unresponsive:
you can see picture from here:
![screenshot](https://github.com/Kritika30032002/To-Do-List-Application/assets/106698498/29e69a2e-45a2-4c36-824d-e873dbf1a6e6)
I can make this responsive.
please assign me this issue under hacktoberfest tag. I will obliged for this.

**Comment by ashfaque-mustaque** [comment]
Ok I am working..

**Comment by Kritika30032002** [comment]
make sure to take the pull of updated branch then check everything is working then create the pr.

**Comment by vinitsingh-13** [comment]
> make sure to take the pull of updated branch then check everything is working then create the pr.

Can I also work it for mobile responsive

**Comment by dipeshhhh** [comment]
It has been 2days+, @ashfaque-mustaque are you still working on it? 
Hey, @Kritika30032002 after you merge new pull requests, you may assign it to me, I can get it done in no time.
Thanks 😄
