### ISSUE TITLE
[BUG] : Dark theme toggle button does not work as it should

### ISSUE THREAD

**Issue by dipeshhhh** [Kritika30032002/To-Do-List-Application#72]
Dark theme toggle button (on the top right) this button should toggle dark theme when clicked the first time, but it is doing after clicking it the second time.

Also clicking it the first time changes the button's theme to dark mode but the whole page is still in light mode, vice versa.

Screenshot:
![image](https://github.com/Kritika30032002/To-Do-List-Application/assets/104263883/8379f82a-32ea-4b25-addd-73616a14f7c3)

**Comment by dipeshhhh** [comment]
I want to work on it.

**Comment by love-sonkar** [comment]
can i work on this issue
