### ISSUE TITLE
[Bug] : The taks item is overflowing from box when you put long task

### ISSUE THREAD

**Issue by love-sonkar** [Kritika30032002/To-Do-List-Application#74]
The task item is overflow from box when user type any long task  

# Screenshot 

![text](https://github.com/Kritika30032002/To-Do-List-Application/assets/82786865/cda10c94-1270-4c5e-ab8b-263c7ea42ecd)

i wanted to work on this issue under hacktoberfest please assign me this

**Comment by Kritika30032002** [comment]
clone the updated repo then start work on this
