### ISSUE TITLE
UI update: I want to update the current UI

### ISSUE THREAD

**Issue by UjjawalGu** [Kritika30032002/To-Do-List-Application#76]
Before UI
![image](https://github.com/Kritika30032002/To-Do-List-Application/assets/121127299/732f9001-1fee-45e0-8811-f6428d640242)

After upgradation
![image](https://github.com/Kritika30032002/To-Do-List-Application/assets/121127299/56b43c0e-7a3c-490b-9685-413c9d7dd6d6)

Kindly assign this task to me so I can upgrade the UI

**Comment by Kritika30032002** [comment]
UI is not looking good
