### ISSUE TITLE
Due date passed issue

### ISSUE THREAD

**Issue by halcyon-past** [Kritika30032002/To-Do-List-Application#79]
![image](https://github.com/Kritika30032002/To-Do-List-Application/assets/70253408/0a8e4934-b8c0-4f60-9e93-2b48ce2aa3ce)

# Issue
The Website does not show if the task has already passed it's due date

suppose the due date is 1st of october 2023
but the date today is 5th of october 2023

# Suggestion:

The website will show the such tasks color in red and beside the due date it will say "Due date is over"

**Comment by Kritika30032002** [comment]
and it should allow to click submit in this case
