### ISSUE TITLE
minor problem in theme switching

### ISSUE THREAD

**Issue by giridhar-cp** [Kritika30032002/To-Do-List-Application#89]
when the website is opened it is in light theme but the toggle switch is in dark mode.after one round usage of the toggle switch it is working well.

**Comment by GeorgeET15** [comment]
Hi can I work on this, can you assign this issue to me.

**Comment by sushilmagare10** [comment]
Hello i can work on this **@Kritika30032002**

**Comment by dipeshhhh** [comment]
I am working on it.
